

[general]

import = [
  "~/.config/alacritty/theme.toml"
]

[window]

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[keyboard]

bindings = [
  { key = "n", mods = "Control", action="SpawnNewInstance"},
  { key = "q", mods = "Control", action="Quit"},
]

[env]
TERM = "xterm-256color"
